include ${ThemePath}/Theme/kitty.conf

# Fonts:
font_family      JetBrainsMono Nerd Font
font_size 12.0

# Cursor:
cursor_shape block
shell_integration no-cursor
cursor_trail 200
cursor_trail_decay 0.1 0.4
cursor_trail_start_threshold 2
touch_scroll_multiplier 4

enable_audio_bell no

# Layout:
enabled_layouts splits
map alt+s launch --location=hsplit
map alt+v launch --location=vsplit

map ctrl+shift+k move_window up
map ctrl+shift+h move_window left
map ctrl+shift+l move_window right
map ctrl+shift+j move_window down

map ctrl+h neighboring_window left
map ctrl+l neighboring_window right
map ctrl+k neighboring_window up
map ctrl+j neighboring_window down

# Window:
window_padding_width 20
confirm_os_window_close 0
background_opacity 0.7
background_blur 7
dynamic_background_opacity yes

# Misc
shell .
allow_remote_control yes

# Binds
map ctrl+shift+u scroll_page_up
map ctrl+shift+d scroll_page_down
map alt+c close_window
