music_directory    "$XDG_MUSIC_DIR"
playlist_directory "{ThemePath}/Theme/mpd/playlists"
db_file            "{ThemePath}/Theme/mpd/database"
log_file           "{ThemePath}/Theme/mpd/log"
pid_file           "{ThemePath}/Theme/mpd/pid"
state_file         "{ThemePath}/Theme/mpd/state"
sticker_file       "{ThemePath}/Theme/mpd/sticker.sql"

auto_update	"yes"

audio_output {
   type   "fifo"
   name   "my_fifo"
   path   "/tmp/mpd.fifo"
   format "44100:16:2"
}
audio_output {
  type "pipewire"
  name "PipeWire Sound Server"
}
